development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://kfjcobeskhqocf:1tPvHehCgGKyejskuAGI1_cudO@ec2-54-163-245-32.compute-1.amazonaws.com:5432/dbbkblu0fad71m
